name: Deployment-WebSite
  hosts: DEVELOP
  tasks: 

    - name: Detener Contenedores Existentes
      shell: sudo docker stop $(sudo docker ps -aq)

    - name: Eliminar Contenedores Existentes
      shell: sudo docker rm $(sudo docker ps -aq) -f

    - name: Eliminar Imagenes Existentes
      shell: sudo docker rmi $(sudo docker images -a -q)
      
    - name: Creamos e Iniciamos el nuevo contenedor
      shell: sudo docker run -d -p 8081:80 --name practicas -it bitochepe/dev

- name: 
  hosts: PRODUCTION
  tasks: 

    - name: Detener Contenedores Existentes
      shell: sudo docker stop $(sudo docker ps -aq)

    - name: Eliminar Contenedores Existentes
      shell: sudo docker rm $(sudo docker ps -aq) -f

    - name: Eliminar Imagenes Existentes
      shell: sudo docker rmi $(sudo docker images -a -q)
      
    - name: Creamos e Iniciamos el nuevo contenedor
      shell: sudo docker run -d -p 8082:80 --name practicas -it bitochepe/dev
