---
- name: Deployment-Servers
  hosts: SERVERS
  tasks: 

    - name: Docker
      shell: 
        cmd: sudo docker-compose -f /home/juanjohr97/docker-compose.yml up --build
        chdir: /home/juanjohr97/

