---
- name: Deployment-Servers
  hosts: SERVERS
  tasks: 
    - name: Creating docker-compose file
    copy:
      dest: "/home/juanjohr97/docker-compose.yml"
      content: |
        version: "3.3"
        services:
          server_client:
            image: bitochepe/sa_server_client
            container_name: client
            ports:
              - "5000:5000"
            restart: on-failure
          server_equipo:
            image: bitochepe/sa_server_equipo
            container_name: team
            ports:
              - "5001:5001"
            restart: on-failure
          server_partido:
            image: bitochepe/sa_server_partido
            container_name: match
            ports:
              - "5002:5002"
            restart: on-failure
          server_competition:
            image: bitochepe/sa_server_competition
            container_name: comp
            ports:
              - "5003:5003"
            restart: on-failure
          server_stadium:
            image: bitochepe/sa_server_stadium
            container_name: stadium
            ports:
              - "5004:5004"
            restart: on-failure
          server_tecnico:
            image: bitochepe/sa_server_tecnico
            container_name: coach
            ports:
              - "5005:5005"
            restart: on-failure
          server_jugador:
            image: bitochepe/sa_server_jugador
            container_name: player
            ports:
              - "5006:5006"
            restart: on-failure
          server_news:
            image: bitochepe/sa_server_news
            container_name: news
            ports:
              - "5007:5007"
            restart: on-failure
          # server_predict:
          #   image: bitochepe/sa_server_prediccion
          #   container_name: predict
          #   ports:
          #     - "5009:5009"
          #   restart: on-failure
          server_auth:
            image: bitochepe/sa_server_auth
            container_name: auth
            ports:
              - "5010:5010"
            restart: on-failure
          server_admin:
            image: bitochepe/sa_server_admin
            container_name: admin
            ports:
              - "5011:5011"
            restart: on-failure
          server_empleado:
            image: bitochepe/sa_server_empleado
            container_name: empleado
            ports:
              - "5012:5012"
            restart: on-failure
          server_pais:
            image: bitochepe/sa_server_pais
            container_name: pais
            ports:
              - "5013:5013"
            restart: on-failure
          # frontend:
          #   image: bitochepe/sa_frontend
          #   container_name: frontend
          #   ports:
          #     - 80:80
          #   restart: on-failure
    - name: Docker
      shell: sudo docker-compose -f /home/juanjohr97/docker-compose.yml up --build

