

GET http://localhost:5003/user/all HTTP/1.1

###

# ----------    Crear   ----------

# POST http://localhost:5003/user/add HTTP/1.1
# content-type: application/json

# {
#     "name": "Tepo",
#     "lastname": "Kun",
#     "password": "Tepo123/",
#     "email": "gomzalo@outlook.com",
#     "phone": 5668998,
#     "photo": "asdkfhjkasdljfklasdj",
#     "gender": "M",
#     "birth_date": "1997-02-27",
#     "signup_date": "2022-02-28",
#     "address": "Patcizia",
#     "id_pais": 88,
#     "id_estado": 2,
#     "id_rol": 3,
#     "age": 24,
#     "membership": 0
# }

# POST http://localhost:5003/user/add HTTP/1.1
# content-type: application/json

# {
#     "name": "Martha",
#     "lastname": "Debaile",
#     "password": "Marta123/",
#     "email": "mclwithmusic@gmail.com",
#     "phone": 5668998,
#     "photo": "asdkfhjkasdljfklasdj",
#     "gender": "M",
#     "birth_date": "1993-02-27",
#     "signup_date": "2022-03-01",
#     "address": "Zona 10",
#     "id_pais": 88,
#     "id_estado": 2,
#     "id_rol": 2,
#     "age": 33,
#     "membership": 0
# }

# Wrong email test

POST http://localhost:5003/user/add HTTP/1.1
content-type: application/json

{
    "name": "Martha",
    "lastname": "Debaile",
    "password": "Marta123/",
    "email": "f45asd4f56@gmail.com",
    "phone": 5668998,
    "photo": "asdkfhjkasdljfklasdj",
    "gender": "M",
    "birth_date": "2001-02-27",
    "signup_date": "2022-03-03",
    "address": "Zona 14",
    "id_pais": 88,
    "id_estado": 2,
    "id_rol": 3,
    "age": 21,
    "membership": 3
}

###

GET http://localhost:5003/user/email_confirmation?id=1 HTTP/1.1

###

# ----------    Login   ----------

POST http://localhost:5003/user/login HTTP/1.1
content-type: application/json

{
    "email": "gomzalo@outlook.com",
    "password": "Tepo123/"
}

# POST http://localhost:5003/user/login HTTP/1.1
# content-type: application/json

# {
#     "email": "gxmzalx@gmail.com",
#     "password": "Bicho123/"
# }

###

POST http://localhost:5003/user/send_email_confirmation HTTP/1.1
content-type: application/json

{
    "email": "gomzalo@outlook.com"
}

###

GET http://localhost:5003/user/all_countries HTTP/1.1

# *******************************************
# ************** CLIENT SERVER ************** 
# *******************************************

GET http://localhost:5000/client/all HTTP/1.1

###

# ----------    Crear   ----------

POST http://localhost:5000/client/add HTTP/1.1
content-type: application/json

{
    "name": "Ay mi madre",
    "lastname": "El bicho",
    "password": "Bicho123/",
    "email": "gxmzalx@gmail.com",
    "phone": 5668998,
    "photo": "asdkfhjkasdljfklasdj",
    "gender": "M",
    "birth_date": "1985-02-05",
    "signup_date": "2022-03-01",
    "address": "Funchal, Portugal",
    "id_pais": 172,
    "id_estado": 2,
    "id_rol": 3,
    "age": 37,
    "membership": 0
}

###

POST http://localhost:5000/client/send_email_confirmation HTTP/1.1
content-type: application/json

{
    "email": "gomzalo@outlook.com"
}

###

GET http://localhost:5000/client/email_confirmation?id=4 HTTP/1.1

###

GET http://localhost:5000/client/all_countries HTTP/1.1


###

# ***************************************************
# ************** ADMINISTRATIVE SERVER ************** 
# ***************************************************

# :::::::::::::::::     STADIUM     :::::::::::::::::

# ----------    Crear   ----------

POST http://localhost:5001/administrative/stadium HTTP/1.1
content-type: application/json

{
    "name": "Spotify Camp Nou",
    "fundation_date": "1985-02-05",
    "capacity": "5566224",
    "id_country": "100",
    "address": "Cumeada, Portugal",
    "state": "Catalunya",
    "photo": "Masdkfjasdlkjfkmasdcmkjlasdnijfnasdlkfj"
}

###

# ----------    Editar   ----------

PUT http://localhost:5001/administrative/stadium HTTP/1.1
content-type: application/json

{
    "id": 5,
    "name": "Santiago Bernaleo",
    "fundation_date": "1940-02-05",
    "capacity": "5566224",
    "id_country": "100",
    "address": "Chamartin, Madrid",
    "state": "Chamartin",
    "photo": "Masdkfjasdlkjfkmasdcmkjlasdnijfnasdlkfj"
}

###

# ----------    Get   ----------

GET http://localhost:5001/administrative/stadium/?id=5 HTTP/1.1
content-type: application/json

###

GET http://localhost:5001/administrative/stadium/ HTTP/1.1
content-type: application/json

###

# ----------    Delete   ----------

DELETE http://localhost:5001/administrative/stadium/?id=3 HTTP/1.1
content-type: application/json

# :::::::::::::::::     COMPETICION     :::::::::::::::::

###

# ----------    Get   ----------

GET http://localhost:5001/administrative/competition/?championship=1 HTTP/1.1
content-type: application/json

###

GET http://localhost:5001/administrative/competition/ HTTP/1.1
content-type: application/json

###

# ----------    Crear   ----------

POST http://localhost:5001/administrative/competition HTTP/1.1
content-type: application/json

{
    "name": "Liga granjera de Guatemala",
    "type": "Liga",
    "year": 2020,
    "champion_team": 1,
    "country": 21
}

###

# ----------    Editar   ----------

PUT http://localhost:5001/administrative/competition HTTP/1.1
content-type: application/json

{
    "id_competition": 2,
    "name": "Liga granjera de El Salvador",
    "type": "Liga",
    "year": 2021,
    "champion_team": 1,
    "country": 22
}

###

# ----------    Delete   ----------

DELETE http://localhost:5001/administrative/competition/?id=4 HTTP/1.1
content-type: application/json

# :::::::::::::::::     PARTIDO     :::::::::::::::::

###

# ----------    Get   ----------

GET http://localhost:5001/administrative/soccer-game/?id=3 HTTP/1.1
content-type: application/json

###

GET http://localhost:5001/administrative/soccer-game/ HTTP/1.1
content-type: application/json

###

# ----------    Crear   ----------

POST http://localhost:5001/administrative/soccer-game HTTP/1.1
content-type: application/json

{
    "game_date": "2022-03-16",
    "attendees": 50688,
    "result_local": 2,
    "result_visiting": 1,
    "state": "unstarted",
    "id_stadium": 1,
    "id_team_local": 1,
    "id_team_visiting": 1,
    "id_competition": 5
}

###

# ----------    Editar   ----------

PUT http://localhost:5001/administrative/soccer-game HTTP/1.1
content-type: application/json

{
    "id_game": 1,
    "game_date": "2022-03-16",
    "attendees": 50688,
    "result_local": 2,
    "result_visiting": 3,
    "state": "in-progress",
    "id_stadium": 1,
    "id_team_local": 1,
    "id_team_visiting": 1,
    "id_competition": 5
}

###

# ----------    Delete   ----------

DELETE http://localhost:5001/administrative/soccer-game/?id=1 HTTP/1.1
content-type: application/json
