
GET http://localhost:5003/user/all HTTP/1.1

###

# ----------    Crear   ----------

# POST http://localhost:5003/user/add HTTP/1.1
# content-type: application/json

# {
#     "name": "Tepo",
#     "lastname": "Kun",
#     "password": "Tepo123/",
#     "email": "gomzalo@outlook.com",
#     "phone": 5668998,
#     "photo": "asdkfhjkasdljfklasdj",
#     "gender": "M",
#     "birth_date": "1997-02-27",
#     "signup_date": "2022-02-28",
#     "address": "Patcizia",
#     "id_pais": 88,
#     "id_estado": 2,
#     "id_rol": 3,
#     "age": 24,
#     "membership": 0
# }

# POST http://localhost:5003/user/add HTTP/1.1
# content-type: application/json

# {
#     "name": "Martha",
#     "lastname": "Debaile",
#     "password": "Marta123/",
#     "email": "mclwithmusic@gmail.com",
#     "phone": 5668998,
#     "photo": "asdkfhjkasdljfklasdj",
#     "gender": "M",
#     "birth_date": "1993-02-27",
#     "signup_date": "2022-03-01",
#     "address": "Zona 10",
#     "id_pais": 88,
#     "id_estado": 2,
#     "id_rol": 2,
#     "age": 33,
#     "membership": 0
# }

# Wrong email test

POST http://localhost:5003/user/add HTTP/1.1
content-type: application/json

{
    "name": "Martha",
    "lastname": "Debaile",
    "password": "Marta123/",
    "email": "f45asd4f56@gmail.com",
    "phone": 5668998,
    "photo": "asdkfhjkasdljfklasdj",
    "gender": "M",
    "birth_date": "2001-02-27",
    "signup_date": "2022-03-03",
    "address": "Zona 14",
    "id_pais": 88,
    "id_estado": 2,
    "id_rol": 3,
    "age": 21,
    "membership": 3
}

###

GET http://localhost:5003/user/email_confirmation?id=1 HTTP/1.1

###

# *******************************************
# ************** AUTH SERVER ************** 
# *******************************************

# ----------    Login   ----------

POST http://localhost:5010/auth/ HTTP/1.1
content-type: application/json

# {
#     "email": "gxmzalx@gmail.com",
#     "password": "GQfilmIIaf"
# }

{
    "email": "wjosuep13@gmail.com",
    "password": "123"
}

{

}

# POST http://localhost:5003/user/login HTTP/1.1
# content-type: application/json

# {
#     "email": "gxmzalx@gmail.com",
#     "password": "Bicho123/"
# }

###

# ----------    Validar cuenta   ----------

GET http://localhost:5010/auth/?id=44 HTTP/1.1

###

# ----------    Contraseña temporal   ----------

POST http://localhost:5010/auth/temporal-password HTTP/1.1
content-type: application/json

{
    "email": "gxmzalx@gmail.com"
}

###

# ----------    Resetear contraseña   ----------

POST http://localhost:5010/auth/reset-password HTTP/1.1
content-type: application/json

{
    "email": "gxmzalx@gmail.com",
    "temporal_password": "gxmzalx@gmail.com",
    "new_password": "gxmzalx@gmail.com"
}

###

# *******************************************
# ************** CLIENT SERVER ************** 
# *******************************************

GET http://localhost:5000/customer/?id=3 HTTP/1.1

###

GET http://localhost:5000/customer HTTP/1.1

###

# ----------    Crear   ----------

POST http://localhost:5000/customer/register HTTP/1.1
content-type: application/json

{
    "name": "Ay mi madre",
    "lastname": "El bicho",
    "password": "Bicho123/",
    "email": "gonzalo-garcia@outlook.com",
    "phone": 5668998,
    "photo": "asdkfhjkasdljfklasdj",
    "gender": "M",
    "birth_date": "1985-02-05",
    "address": "Funchal, Portugal",
    "id_pais": 172
}

###

# ----------    Editar   ----------

PUT http://localhost:5000/customer/ HTTP/1.1
content-type: application/json

{
    "id": 3,
    "name": "Martha",
    "lastname": "Debaile",
    "password": "Marta123/",
    "email": "gomzalo@outlook.com",
    "phone": 5668998,
    "photo": "asdkfhjkasdljfklasdj",
    "gender": "F",
    "birth_date": "1998-02-27",
    "address": "Zona 14",
    "id_country": 88
}

###

POST http://localhost:5000/customer/membership HTTP/1.1
content-type: application/json

{
    "id_client": 3
}

###

PUT http://localhost:5000/customer/membership HTTP/1.1
content-type: application/json

{
    "id_client": 3
}

###

POST http://localhost:5000/customer/follow HTTP/1.1
content-type: application/json

{
    "id_client": 3,
    "id_team": 5
}
###

# ***************************************************
# ************** TEAM SERVER ************** 
# ***************************************************

###

# ----------    Get   ----------

GET http://localhost:5001/team/?id=1 HTTP/1.1
content-type: application/json

###

GET http://localhost:5001/team/ HTTP/1.1
content-type: application/json

###

# ----------    Crear   ----------

POST http://localhost:5001/team HTTP/1.1
content-type: application/json

{
    "name": "Spotify FC",
    "foundation_date": "1905-02-15",
    "photo": "dsf4545asdf",
    "id_country": 21
}

###

# ----------    Editar   ----------

PUT http://localhost:5001/team HTTP/1.1
content-type: application/json

{
    "id": 7,
    "name": "Spotify FC",
    "foundation_date": "1905-02-15",
    "photo": "a5sd5s55",
    "id_country": 100
}


###

# ----------    Delete   ----------

DELETE http://localhost:5001/team/?id=7 HTTP/1.1

###

# ***************************************************
# ************** STADIUM SERVER ************** 
# ***************************************************

# ----------    Crear   ----------

POST http://localhost:5004/stadium HTTP/1.1
content-type: application/json

{
    "name": "Spotify Camp Nou",
    "fundation_date": "1985-02-05",
    "capacity": "5566224",
    "id_country": "100",
    "address": "Cumeada, Portugal",
    "status": 1,
    "photo": "Masdkfjasdlkjfkmasdcmkjlasdnijfnasdlkfj"
}

###

# ----------    Editar   ----------

PUT http://localhost:5004/stadium HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "Santiago Bernaleo",
    "fundation_date": "1940-02-05",
    "capacity": "5566224",
    "id_country": "100",
    "address": "Chamartin, Madrid",
    "status": 2,
    "photo": "Masdkfjasdlkjfkmasdcmkjlasdnijfnasdlkfj"
}

###

# ----------    Get   ----------

GET http://localhost:5004/stadium/?id=1 HTTP/1.1
content-type: application/json

###

GET http://localhost:5004/stadium/ HTTP/1.1
content-type: application/json

###

# ----------    Delete   ----------

DELETE http://localhost:5004/stadium/?id=1 HTTP/1.1
content-type: application/json

# ***************************************************
# ************** COMPETICION SERVER ************** 
# ***************************************************

###

# ----------    Get   ----------

GET http://localhost:5003/competition/?id=1 HTTP/1.1
content-type: application/json

###

GET http://localhost:5003/competition/ HTTP/1.1
content-type: application/json

###

# ----------    Crear   ----------

POST http://localhost:5003/competition/ HTTP/1.1
content-type: application/json

{
    "name": "Liga granjera de Guatemala",
    "type": 1,
    "year": 2020,
    "id_country": 21
}

###

# ----------    Editar   ----------

PUT http://localhost:5003/competition/ HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "Liga granjera de El Salvador",
    "type": 2,
    "year": 2021,
    "id_champion_team": 1,
    "id_country": 22
}

###

# ----------    Delete   ----------

DELETE http://localhost:5003/competition/?id=1 HTTP/1.1
content-type: application/json

# ***************************************************
# ************** PARTIDO SERVER ************** 
# ***************************************************

###

# ----------    Get   ----------

GET http://localhost:5002/match/?id=11 HTTP/1.1
content-type: application/json

###

GET http://localhost:5002/match/ HTTP/1.1
content-type: application/json

###

# ----------    Crear   ----------

POST http://localhost:5002/match HTTP/1.1
content-type: application/json

{
    "game_date": "2022-03-26",
    "attendees": 56988,
    "result_local": 2,
    "result_visiting": 1,
    "status": 1,
    "id_stadium": 2,
    "id_team_local": 1,
    "id_team_visiting": 1,
    "id_competition": 2
}

###

# ----------    Editar   ----------

PUT http://localhost:5002/match HTTP/1.1
content-type: application/json

{
    "id_game": 11,
    "game_date": "2022-03-16",
    "attendees": 50688,
    "result_local": 2,
    "result_visiting": 3,
    "status": 1,
    "id_stadium": 2,
    "id_team_local": 1,
    "id_team_visiting": 1,
    "id_competition": 2
}

###

# ----------    Delete   ----------

DELETE http://localhost:5002/match/?id=10 HTTP/1.1
content-type: application/json


# ***************************************************
# ************** COUNTRY SERVER ********************* 
# ***************************************************

###

# ----------    Obtener pais   ----------

GET http://localhost:5013/country/?id=1 HTTP/1.1

###

# ----------    Obtener paises   ----------

GET http://localhost:5013/country HTTP/1.1

# *******************************************
# ************** NEWS SERVER ************** 
# *******************************************

# ----------    Crear   ----------

###
POST http://localhost:5007/post HTTP/1.1
content-type: application/json

{
    "id_team": 3,
    "id_user": 1,
    "title": "F por el barsita",
    "description": "ay caramba dijo el bar sinso",
    "date": "2022-03-27"
}

###

# ----------    Obtener     ----------

GET http://localhost:5007/post/?id=3 HTTP/1.1